language: java

jdk:
  - oraclejdk8


os:
  - linux

addons:
  sonarqube:
    token:
      secure: "F9xuSHundhin1l3siqWRJ39sK+ut++F2qiQaMsIvaktDG6wkCKQYC+v7NrVTkPLMcsI/a6ECVpTLBhf04fL8qbKyl9Wzw8RTXqWIEq/TgeVCQUXxJwiGZSYIy0ZvoJROQsslAVE/Qp2+4MEO+5+MqBUIaHPFII315PR19xFln3TW9hFcKy19NWOCHhbI64EWX0nw9OHeJJ6EtOTdRGLrIZzGGgnyRUIm0PM2kqkvaboC01jIdko0f0NVu2Cquoj7S6eUt/seITJxvV0yLjIs1fmHa7YANoflg7ht2EZv5C5Y5Fsi9/TDPksmA2bIx65gl+M7MOlgvSqJL5YsQB+lS3HJjPh1T2PaonoYwbLDLTLJBjpyGOoLa1yIlHcw4nwBalOiz8fs5dv9UOlqCYGU2CBrDKqHAf0SO6DuF9C+vYj9tXgRj87iirkIvyh70S9WVxtMroT1diua+b8ErGL9/1Yt4HSxsdwE3sRnPw9s2/xeck4N22CSZW5Zsp0b5oYLzgZ8eESe2COs5Io0KaCqzXd0mU+sVl5YgwGZ5ssTEfuTwSUROXRHK/KyzOr72Fa5YTbrfiksiz1daEu1OemNP13Zi2FgFWf9vVpbbq29DXlpn2y95cNgObBRuXG9g/+ng1GZZmkjj2JW21geMzkcKn8PhLcqBU6wzORMB+r7zHs="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
