language: java

jdk:
  - oraclejdk8


os:
  - linux

addons:
  sonarqube:
    token:
      secure: "rAl1ujEubgu9BiMmn51p+yOsP3t559K8b5OSY0mduthLRCFhYG2HbxDZtEU48YQv8RWayoWJCNozmVg3aXw7S23+wxjOe5+9ssGxILIkUqbF3BBFnZ4s2wRNOGjlWVz1rlOros13Kh1dQVjAdKf4L68z13dp2b6Tsof4jPvP2Tccf+YBDLgmh1KGId1HeWlxeawyJ79q2+9byD/VDyAtxDX+Lm8LYB1RL0BTv7oUjuyVSgUrIEOPAKvSeXn5/ffvJWuyDTfLOJewS2cqDNg5S/WXbrgu/BBhrUjMGGAbJ2kCdNo7O4BSvU5S8yeC7QLpSpCEpKnuo649dcTbWb/4INjjzmJTJAkvE4EbjpyOWdYSqqZSugJXUleUiU7V8TamZvzGWnDcC5SRvOu2SVWikknuVL9QpXWteE8JMcUrptRWrzguSpvdBWqMqxfhHNGh7BNu+E+dgnFiAcWH2K3eJ23mm0yhOzpw7eD7Nyje2DuyIYQ61DjfgHSdvhiAaFMW4d32LxWa36aOXCEw4vjlRXw0g0LJ4r4A20mjpTboz2G75N/HzUvjsS//o7AdK/DaRhP9fpDnm/3h+t4nFJ0Hj7BJAgFPV6Omd1uyxi7iHlFJowIFJy1yB4AiNoUrnloBfVTYpLAInmuiprmW/v8aNHApgRCVnVFvGbXPt/Ro6MY="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
