dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8


os:
  - linux

addons:
  sonarqube:
    organization: "pitt112-github"
    token:
      secure: "SGegOc5WaPzUBSMatajkVHKhLKietrtaF0Bmj1HwV6rn2B4vu4vL+FwQE9rH4kQqildWL2Ko0umrRdh5VqrUnU61DkrMy5OzG7rV9OogbTQ6QwW49rFQNBh1WEQ2BMTuHQhoo0MlAWUJDKfffIJAOGOKMYUYodeVx3aZg3ZjedsFwjthucY6iWCyChSru+/XRt6UwHQPupqZXBP2mucFg2vO5ulCHkhI/JmuZzPQock+EGMUTL2osyiKnkT/1auEQf5v+fwOQaXqgAJWqLcn1N5h2RAvP8dzkXzrraXptmtdihCrz3Zb0/uURdp2oxbpGIGZB4lw1eggplctT/II3ZTQiJukHjj3ri1Y7L+PhuVLKIh5wDS7t5xDoc3RyDkCYnpzlOCQ7wbz1cLWYlTyLArCH06cZB1voNZt0AY31ZP76lP7MoJi6LWqHAAXJp9X1Q34Qt6S/ndnxvOURZzSDMwBphsttcyUGTIm5BLzs79EAZGRj66YZDdXuhjTJsyXTYEaOwxqIY1g9aM5YAABWBqdiq5rBRwvteKLY3z7SX+xs3fbP9oXNfRQc64MF7LJATZ9xqM7nE45rp256v+z1ya/K7k0PbafgavTD27XiyP4e6C/KIYqnWZ2H249hvCsNCdC54w8qYxCrqnCdbWsIYJVtCHvnvVjtJsGNp9WWHI="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
