language: java

jdk:
  - oraclejdk8


os:
  - linux

#addons:
#  sonarqube:
#    token:
#      secure: "O0JXwjwgX2dFSfu5kRFjiVYkqrF7UT30KTG2nCaVc8wZHxDVijqSGOspd4srPafcaZ2YomGfeZDzxrRhUU7sWQLowElGMSHt25hJ2vuvxmkm8s7nKbuFPYaR+8gIYwwi2ELJOubCUc03IGk9DTDDBrypI/g/L2rbTURlVf7tWkpP/1B9nuGSsO6/oOoJahIFpt5OgtSivj5Rw7GzHupOEOkDL5vAnRNmrWROqcfOsFnwTIiOF5BdIBB+0EeEhG2QMPsfVEIffGm3NAI2jqZCI366R9E7794WlpakP8OGQKwP3q/oG+OC8J/kQPcxqJ84Ev353H55+SlnV/sr1UES4NfpqngV79u9pSP5nfn8miwNrzwnDxRuo0UWrsZCeDHK61CUxBsmJvlm1JnHRJHkXuoMfx8PUtF6iMzdwPZ0Mra4NPQgjHqBfROtuj5KkPKEwEbBgwlFh8ts8RWVrt4m8pFVKs/V9OdmD+4iWjPo5y5ZkHlEfgaiSc5G8MjjY74h9mDuN0ZCz3jPX6esI+RWXKutz6q7YOPC7UUIDMKgZUePQEs5DXuHhFcRSn7CX/5WzpNrSTDbfO3qJ2ySBRwQsBN+ccCrRdm6JS146Crx4KkfgPtxps3CKba25gp7oBqyV1S6KkV5BEs3gjXZMTvpz47MPTNVcXkLsxTFtfZNJ0k="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
