dist: trusty

language: java

jdk:
  - oraclejdk8


os:
  - linux

addons:
  sonarqube:
    token:
      secure: "HhorYY/iSUmt8V5Mf5+oQY8Rl2IckApxndxtW/WT9f/C2Qi2titrkRxtmBAjQZCAT3Vl/JGV/djyO0BDgDxxcRhU5FheRR9CxD0xqtOGLQuA7Vz9ICHUDkwA4jctLTomyAr9VaqCq687SwYTyUGaxRUrQnERQOfVD5jLGGqNTiuI9Qg78PCltPyB6hnjDynQtkPO4QwMOILNB+YT9QHVnZw9pxj+B4WfIMxPBOSGkzaeqwguLRfmEFKb6iLe0KIp1HF1kIfIWS+jghStamZ6FAKJCtAsmIhd5w2kGIqNFo2x6UWHKd+vTR/oIQBF3xuYE2xUrjccs/E9ZdsH5IuXiSNCIInuc170y0HTCCZ519oGhCnkw4rq2gZVRSDqF135yxPROtU88jYY++KI6YYfiWyp585H0J3KO5El1LquHtNmeLdM6HbSZSXalvn0wODNzlZ7cnqlzuU4stTK9LeqcnPULSlEtH+ceARKMOraQRC5Z/ZWfzO5JyHWi+Ldj1QT+L8G25XNrWRHSSZF+6Pjg7BOdAUtdmk2obnm3FEAU3ZlLRQ0TmSBfG2iljgbb4eeJVMSMrVwQ53eobNp9Pf7ONv3XAi/MuC+jcObetHt5I4izSbadopV5UWsqlY0L6UhPb3jSf+tdoLahq9wq0aQ5ND1zBz4UJotCZjEyFMTxMU="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
